/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author linus
 */
public class ForgotPasswordWindow extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordWindow
     */
    public ForgotPasswordWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PasswordReset = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        StudentIDTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        ForgotPasswordBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordReset.setBackground(new java.awt.Color(53, 64, 142));
        PasswordReset.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        PasswordReset.setForeground(new java.awt.Color(255, 255, 255));
        PasswordReset.setText("Password Reset");
        PasswordReset.setFocusPainted(false);
        PasswordReset.setPreferredSize(new java.awt.Dimension(211, 36));
        PasswordReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordResetActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 740, 570, 60));

        CancelBtn.setBackground(new java.awt.Color(153, 153, 153));
        CancelBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelBtn.setText("Cancel");
        CancelBtn.setFocusPainted(false);
        CancelBtn.setPreferredSize(new java.awt.Dimension(211, 36));
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 810, 570, 50));

        StudentIDTF.setBackground(new java.awt.Color(242, 242, 242));
        StudentIDTF.setForeground(new java.awt.Color(153, 153, 153));
        StudentIDTF.setText("Enter Student ID");
        StudentIDTF.setBorder(null);
        StudentIDTF.setMargin(new java.awt.Insets(6, 6, 2, 6));
        StudentIDTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentIDTFMouseClicked(evt);
            }
        });
        jPanel1.add(StudentIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 622, 550, 50));

        EmailTF.setBackground(new java.awt.Color(242, 242, 242));
        EmailTF.setForeground(new java.awt.Color(153, 153, 153));
        EmailTF.setText("Enter Email");
        EmailTF.setBorder(null);
        EmailTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailTFMouseClicked(evt);
            }
        });
        jPanel1.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 550, 50));

        ForgotPasswordBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ForgotPasswordBackground.png"))); // NOI18N
        jPanel1.add(ForgotPasswordBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordResetActionPerformed
        
    }//GEN-LAST:event_PasswordResetActionPerformed

    private void StudentIDTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentIDTFMouseClicked
        StudentIDTF.setText("");
    }//GEN-LAST:event_StudentIDTFMouseClicked

    private void EmailTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTFMouseClicked
        EmailTF.setText("");
    }//GEN-LAST:event_EmailTFMouseClicked

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        LoginPage GoToLoginPage = new LoginPage();
        GoToLoginPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JLabel ForgotPasswordBackground;
    private javax.swing.JButton PasswordReset;
    private javax.swing.JTextField StudentIDTF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
