/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.*;

public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        EnterPasswordJField = new javax.swing.JTextField();
        EnterNameJField = new javax.swing.JTextField();
        CreateAccBtn = new javax.swing.JButton();
        SignInBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnterPasswordJField.setBackground(new java.awt.Color(242, 242, 242));
        EnterPasswordJField.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        EnterPasswordJField.setForeground(new java.awt.Color(153, 153, 153));
        EnterPasswordJField.setText("Enter Your Password");
        EnterPasswordJField.setBorder(null);
        EnterPasswordJField.setMinimumSize(new java.awt.Dimension(63, 22));
        EnterPasswordJField.setPreferredSize(new java.awt.Dimension(50, 22));
        EnterPasswordJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterPasswordJFieldMouseClicked(evt);
            }
        });
        jPanel3.add(EnterPasswordJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 496, 329, 30));

        EnterNameJField.setBackground(new java.awt.Color(242, 242, 242));
        EnterNameJField.setColumns(1);
        EnterNameJField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        EnterNameJField.setForeground(new java.awt.Color(153, 153, 153));
        EnterNameJField.setText("Enter Your Name");
        EnterNameJField.setBorder(null);
        EnterNameJField.setCaretPosition(0);
        EnterNameJField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EnterNameJField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        EnterNameJField.setMinimumSize(new java.awt.Dimension(63, 22));
        EnterNameJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterNameJFieldMouseClicked(evt);
            }
        });
        jPanel3.add(EnterNameJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 435, 329, 30));

        CreateAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        CreateAccBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        CreateAccBtn.setText("Create An Account");
        CreateAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccBtnActionPerformed(evt);
            }
        });
        jPanel3.add(CreateAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 568, 165, 44));

        SignInBtn.setBackground(new java.awt.Color(0, 51, 153));
        SignInBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignInBtn.setText("Sign In");
        SignInBtn.setBorder(null);
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });
        jPanel3.add(SignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 568, 165, 44));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNameJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterNameJFieldMouseClicked
        EnterNameJField.setText("");
        EnterNameJField.setForeground(Color.BLACK);
    }//GEN-LAST:event_EnterNameJFieldMouseClicked

    private void EnterPasswordJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterPasswordJFieldMouseClicked
        EnterPasswordJField.setText("");
        EnterPasswordJField.setForeground(Color.BLACK);
    }//GEN-LAST:event_EnterPasswordJFieldMouseClicked

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        MainWindow GoToMainWindow = new MainWindow();
        GoToMainWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void CreateAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccBtnActionPerformed
        SignUpPage GoToSignUpPage = new SignUpPage();
        GoToSignUpPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreateAccBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccBtn;
    private javax.swing.JTextField EnterNameJField;
    private javax.swing.JTextField EnterPasswordJField;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
